# Generated by Django 4.2.4 on 2023-08-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_email', models.CharField(max_length=120)),
                ('reg_password', models.CharField(max_length=120)),
            ],
        ),
    ]
