# Generated by Django 4.2.4 on 2023-08-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin_email',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='code_country',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='firstname',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='national_id',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='passport_expire_date',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='passport_number',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
