# Generated by Django 4.2.4 on 2023-08-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.CharField(default='00/00/0000', help_text='format - 00/00/0000', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others / Transgender', 'Others / Transgender')], default='00/00/0000', max_length=25),
            preserve_default=False,
        ),
    ]
