# Generated by Django 4.2.4 on 2023-08-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_date_of_birth_alter_client_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='cities',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients', to='core.city'),
        ),
    ]
