# Generated by Django 4.2.4 on 2023-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_client_visa_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='clients', to='core.city'),
        ),
    ]
