# Generated by Django 4.2.4 on 2023-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_client_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='visa_sub_category',
            field=models.CharField(choices=[('Driver D-visa', 'Driver D-visa'), ('Karta Polaka D-visa', 'Karta Polaka D-visa'), ('Other D-visa', 'Other D-visa'), ('Postal D-visa', 'Postal D-visa'), ('Work D-visa', 'Work D-visa'), ('D - National', 'D - National'), ('D - National Visa', 'D - National Visa'), ('D - Student', 'D - Student'), ('D - Student Visa', 'D - Student Visa'), ('D - Uczen', 'D - Uczen'), ('D - Uczen Visa', 'D - Uczen Visa'), ('PBH D-visa', 'PBH D-visa'), ('D - PBH', 'D - PBH'), ('D - PBH Visa', 'D - PBH Visa')], max_length=50),
        ),
    ]
