# Generated by Django 4.2.4 on 2023-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_client_visa_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code_country',
            field=models.IntegerField(default=0, help_text='375'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.IntegerField(default=0, help_text='9 digits'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_expire_date',
            field=models.CharField(help_text='format - 00112222', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_number',
            field=models.CharField(help_text='format - mp1234567', max_length=100),
        ),
    ]
